name: Python CI

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_YT_API_KEY: ${{ secrets.GOOGLE_YT_API_KEY }}
      run: |
        python main.py

    - name: Upload downloaded files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: downloaded-files
        path: |
            output_video.mp4
