name: Python CI

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_YT_API_KEY: ${{ secrets.GOOGLE_YT_API_KEY }}
      run: |
        python main.py

    - name: Upload downloaded files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: downloaded-files
        path: |
            output_video.mp4
    - name: Authenticate with Google and get Access Token
      id: oauth
      run: |
        python - <<EOF
        import os
        import google_auth_oauthlib.flow
        from google.oauth2.credentials import Credentials
        from google.auth.transport.requests import Request
        
        # Load the client secrets from GitHub secrets
        client_id = os.getenv('CLIENT_ID')
        client_secret = os.getenv('CLIENT_SECRET')
        
        # OAuth 2.0 flow
        client_secrets = {
            "installed": {
                "client_id": client_id,
                "client_secret": client_secret,
                "redirect_uris": ["http://localhost"]
            }
        }
        
        # Create the OAuth flow
        flow = google_auth_oauthlib.flow.InstalledAppFlow.from_client_config(client_secrets, ['https://www.googleapis.com/auth/youtube.upload'])
        
        # Run local server and obtain credentials
        credentials = flow.run_local_server(port=0)
        
        # Save the credentials for future use (could store in a secret if needed)
        access_token = credentials.token
        print(f"::set-output name=access_token::{access_token}")
        EOF

    - name: Set Access Token as Environment Variable
      run: echo "ACCESS_TOKEN=${{ steps.oauth.outputs.access_token }}" >> $GITHUB_ENV

    - name: Upload video to YouTube
      run: |
        curl -X POST \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          -F "snippet={\"title\": \"Your Video Title\", \"description\": \"Your video description\", \"tags\": [\"tag1\", \"tag2\"]}" \
          -F "status={\"privacyStatus\": \"public\"}" \
          -F "media=output_video.mp4" \
          "https://www.googleapis.com/upload/youtube/v3/videos?uploadType=multipart&part=snippet,status"

