name: Run Python Script

on:
  pull_request:
    branches:
      - main

jobs:
  generate_text:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Important: Required for Workload Identity Federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud (Workload Identity Federation)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/157416855050/locations/global/workloadIdentityPools/github-actions-yt-push/providers/github'
          service_account: 'yt-push-user@yt-push-451006.iam.gserviceaccount.com'
          create_credentials_file: false  # No need for credentials file if you use Workload Identity Federation

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-generativeai

      - name: Run generative AI script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file }}  # Use the credentials file from auth action
        run: |
          python generate_quote.py