name: List services in GCP
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: 'checkout'
      name: 'Checkout code'
      uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v2'
      with:
          workload_identity_provider: 'projects/157416855050/locations/global/workloadIdentityPools/github-actions-yt-push/providers/github'
          service_account: 'yt-push-user@yt-push-451006.iam.gserviceaccount.com'
          create_credentials_file: true 
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud services list
