name: Run Python Script 3

on:
  push:
    branches:
      - development

jobs:
  generate_text:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Important: Required for Workload Identity Federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client
            
      - name: Drive Check
        env:
          GCP_API_KEY: ${{ secrets.GOOGLE_API_KEY_DRIVE }}  # Pass secret to script
        run: |
          python drive_check.py
