name: Download Files from Google Drive

on:
  push:
    branches:
      - development

jobs:
  download-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client
          pip install google-auth-httplib2
          pip install google-auth-oauthlib
          pip install Pillow 
          pip install requests
          pip install pygame
          pip install numpy
          pip install moviepy==1.0.3

      - name: Run Python script to download files
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          python drive_check.py

      - name: Upload downloaded files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-files
          path: |
            output_bg.png
            output_video.mp4
