name: Google Drive Files List

on:
  push:
    branches:
      - development

jobs:
  list_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client
        pip install google-auth-httplib2
        pip install google-auth-oauthlib # Install your dependencies

    - name: Upload token.pickle as a GitHub secret
      uses: actions/upload-artifact@v4
      with:
        name: token-pickle
        path: token.pickle

    - name: Run Python script to list files from Google Drive
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}  # Your credentials JSON stored in GitHub Secrets
      run: |
        python drive_check.py
